services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongo_data:/data/db
  backend:
    build: ./backend
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    depends_on:
      - backend
volumes:
  mongo_data: