export const SERVICE_STATUS = {
    PENDING: "PENDING",
    ASSIGNED: "ASSIGNED",
    IN_PROGRESS: "IN_PROGRESS",
    WAITING_PARTS: "WAITING_PARTS",
    FINISHED: "FINISHED",
    DELIVERED: "DELIVERED",
    CANCELLED: "CANCELLED"
};